version: '3'

services:
  library:
    build: .
    container_name: sc_web
    ports:
      - <APP_PORT>
    volumes:
     - <LOGS_PATH>:/var/logs
     - <APP_PATH>:/var/www/html/

networks:
  default:
    external:
      name: <DOCKER_NETWORK>
